"""Demo seed (Phase 9): idempotent fixture creation for the walkthrough.

Creates the demo org, its users, two document types, two trusted references
(generated by ReportLab in-process) and two counterfeit submissions that the
worker already verified, so the FLAGGED path demos end-to-end.
"""
from .extensions import db
from .models.apikey import APIKey
from .models.common import RoleCode, StatusCode
from .models.domain import (
    DocumentType,
    QueueTask,
    ReferenceDocument,
    Verification,
    VerificationStatus,
)
from .models.organization import Membership, Organization
from .repositories.index import OrganizationRepository, UserRepository
from .services.audit import AuditService
from .services.demo import (
    ADMISSION_GENUINE,
    COUNTERFEIT_ADMISSION,
    COUNTERFEIT_TRANSCRIPT,
    TRANSCRIPT_GENUINE,
    make_counterfeit,
    render_admission_pdf,
    render_transcript_pdf,
)
from .services.references import process_reference
from .services.storage import get_storage
from .services.verification.concrete import sha256_hex


def _ensure_org():
    org = OrganizationRepository().get_by_slug("demo")
    if org is None:
        org = Organization(name="Demo University of Technology", slug="demo", industry="University")
        db.session.add(org)
        db.session.flush()
    return org


def _ensure_user(email, full_name, password, org, role):
    repo = UserRepository()
    user = repo.get_by_email(email)
    if user is None:
        user = repo.create_user(email, full_name, password)
        db.session.flush()
    membership = next(
        (m for m in user.active_memberships() if m.organization_id == org.id), None
    )
    if membership is None:
        membership = Membership(user_id=user.id, organization_id=org.id,
                                role=RoleCode(role), status=StatusCode.ACTIVE)
        db.session.add(membership)
    else:
        membership.role = RoleCode(role)
        membership.status = StatusCode.ACTIVE
    return user, membership


def _ensure_document_type(org_id, code, name, fields, description):
    existing = DocumentType.query.filter_by(organization_id=org_id, code=code).first()
    if existing:
        return existing
    row = DocumentType(organization_id=org_id, name=name, code=code,
                       description=description, fields=fields,
                       status=StatusCode.ACTIVE)
    db.session.add(row)
    return row


def _ensure_reference(org_id, doc_type, record, kind):
    existing = ReferenceDocument.query.filter_by(organization_id=org_id).filter(
        ReferenceDocument.title == record.title).first()
    if existing:
        return existing
    data = render_transcript_pdf(record) if kind == "transcript" else render_admission_pdf(record)
    payload = process_reference(org_id, filename=f"{kind}-genuine.pdf", data=data,
                                document_type_id=doc_type.id, title=record.title,
                                ref_code=f"REF-{kind.upper()}-0001",
                                fields_config=doc_type.fields)
    row = ReferenceDocument(**payload)
    db.session.add(row)
    return row


def _ensure_counterfeit_verification(org_id, doc_type, ref, record, kind):
    existing = Verification.query.filter_by(organization_id=org_id).filter(
        Verification.filename == f"counterfeit-{kind}.pdf").first()
    if existing:
        return existing
    genuine = render_transcript_pdf(ref.pdf_record) if kind == "transcript" else \
        render_admission_pdf(ref.pdf_record)
    data = make_counterfeit(genuine, record)
    storage = get_storage()
    path = storage.save(org_id, "submissions", f"counterfeit-{kind}.pdf", data)
    ver = Verification(
        organization_id=org_id,
        reference_id=ref.id,
        document_type_id=doc_type.id,
        created_by=None,
        filename=f"counterfeit-{kind}.pdf",
        storage_path=path,
        checksum=sha256_hex(data),
        status=VerificationStatus.SUBMITTED,
    )
    db.session.add(ver)
    db.session.flush()
    QueueTask.enqueue(organization_id=org_id, kind="VERIFY_DOCUMENT",
                      payload={"verification_id": ver.id})
    return ver


def seed_demo(*, create_api_key: bool = True, queue_work: bool = True) -> dict:
    org = _ensure_org()
    org_id = org.id

    admin, _ = _ensure_user("admin@demo.edu", "Demo Administrator",
                            "verifo-demo-admin", org, RoleCode.ADMIN.value)
    operator, _ = _ensure_user("operator@demo.edu", "Dana Operator",
                               "VerifoDemo123!", org, RoleCode.OPERATOR.value)
    submitter, _ = _ensure_user("student@demo.edu", "Adaeze Okafor",
                                "VerifoDemo123!", org, RoleCode.SUBMITTER.value)

    transcript_type = _ensure_document_type(
        org_id, "TRANSCRIPT_2026", "Transcript — 2026",
        ["name", "matric", "programme", "cgpa", "session", "level"],
        "Official academic transcript.")
    admission_type = _ensure_document_type(
        org_id, "ADMISSION_2026", "Admission Letter — 2026",
        ["name", "matric", "programme", "session", "level"],
        "Official letter of admission.")

    class _R:
        pass

    transcript_ref = _R()
    transcript_ref.id = _ensure_reference(org_id, transcript_type, TRANSCRIPT_GENUINE,
                                          "transcript").id
    transcript_ref.pdf_record = TRANSCRIPT_GENUINE
    admission_ref = _R()
    admission_ref.id = _ensure_reference(org_id, admission_type, ADMISSION_GENUINE,
                                         "admission").id
    admission_ref.pdf_record = ADMISSION_GENUINE

    _ensure_counterfeit_verification(org_id, transcript_type, transcript_ref,
                                     COUNTERFEIT_TRANSCRIPT, "transcript")
    _ensure_counterfeit_verification(org_id, admission_type, admission_ref,
                                     COUNTERFEIT_ADMISSION, "admission")

    if create_api_key and not APIKey.query.filter_by(organization_id=org_id).first():
        key, _raw = APIKey.generate(org_id, "Demo integration", admin.id, ttl_days=365)
        db.session.add(key)

    AuditService.commit(organization_id=org_id, action="DEMO_SEEDED",
                        entity_type="Organization", entity_id=org_id,
                        summary="Demo fixtures (references + counterfeits) seeded.")
    db.session.commit()
    return {"organization_id": org_id}